sudo: required

language: csharp
mono: none
dist: xenial
dotnet: 3.1

script:
  - dotnet tool install --global minicover
  - dotnet restore
  - dotnet build
  - minicover instrument --sources Katas/**/*.cs --tests KatasTests/**/*.cs
  - minicover reset
  - dotnet test --no-build

after_success:
  - minicover uninstrument
  - minicover coberturareport
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
