sudo: required

language: csharp
mono: none
dist: xenial
dotnet: 3.1

script:
  - dotnet tool install minicover
  - dotnet restore
  - dotnet build
  - dotnet minicover instrument --sources Katas/**/*.cs --tests KatasTests/**/*.cs
  - dotnet minicover reset
  - dotnet test --no-build

after_success:
  - dotnet minicover uninstrument
  - dotnet minicover coberturareport
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
